apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fx68lvpv0-python
  janus-idp.io/tekton: fx68lvpv0-python
  backstage.io/kubernetes-id: fx68lvpv0-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: fx68lvpv0-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
